# Gateway服务配置
server_settings:
  host: ${ICHAT_GW_HOST:-0.0.0.0}
  port: ${ICHAT_GW_PORT:-8080}
  log_level: ${ICHAT_GW_LOG_LEVEL:-info}

# Gateway自动管理的Worker配置
# Gateway会根据此列表自动启动和管理Worker进程
managed_workers:
  - model_name: ${ICHAT_WORKER_MODEL_NAME:-/mnt/models}
    model_path: ${ICHAT_WORKER_MODEL_PATH:-/mnt/models}
    backend: ${ICHAT_WORKER_BACKEND:-vllm}
    gpu_ids: ${ICHAT_WORKER_GPU_IDS}
    port: ${ICHAT_WORKER_PORT:-8001}
    heartbeat_interval: ${ICHAT_WORKER_HEARTBEAT_INTERVAL:-10}
    # 以下为透传给 vLLM/SGLang 的参数
    context_length: ${ICHAT_WORKER_CONTEXT_LENGTH}
    tensor_parallel_size: ${ICHAT_WORKER_TENSOR_PARALLEL_SIZE}
    gpu_memory_utilization: ${ICHAT_WORKER_GPU_MEMORY_UTILIZATION}
